#!/bin/bash
LIB=polymer_ui_elements
LIB=$LIB,polymer_ui_accordion
LIB=$LIB,polymer_ui_animated_pages
LIB=$LIB,polymer_ui_arrow
LIB=$LIB,polymer_ui_breadcrumbs
LIB=$LIB,polymer_ui_card
LIB=$LIB,polymer_ui_collapsible
LIB=$LIB,polymer_ui_field
LIB=$LIB,polymer_ui_icon
LIB=$LIB,polymer_ui_icon_button
LIB=$LIB,polymer_ui_menu
LIB=$LIB,polymer_ui_menu_button
LIB=$LIB,polymer_ui_menu_item
LIB=$LIB,polymer_ui_nav_arrow
LIB=$LIB,polymer_ui_overlay
LIB=$LIB,polymer_ui_pages
LIB=$LIB,polymer_ui_rating
LIB=$LIB,polymer_ui_scaffold
LIB=$LIB,polymer_ui_sidebar
LIB=$LIB,polymer_ui_sidebar_header
LIB=$LIB,polymer_ui_sidebar_menu
LIB=$LIB,polymer_ui_splitter
LIB=$LIB,polymer_ui_submenu_item
LIB=$LIB,polymer_ui_tabs
LIB=$LIB,polymer_ui_theme_aware
LIB=$LIB,polymer_ui_toggle_button
LIB=$LIB,polymer_ui_toolbar

LIB=$LIB,polymer_ajax
LIB=$LIB,polymer_anchor_point
LIB=$LIB,polymer_animation
LIB=$LIB,polymer_collapse
LIB=$LIB,polymer_cookie
LIB=$LIB,polymer_file
LIB=$LIB,polymer_flex_layout
LIB=$LIB,polymer_google_jsapi
LIB=$LIB,polymer_grid_layout
LIB=$LIB,polymer_jsonp
LIB=$LIB,polymer_key_helper
LIB=$LIB,polymer_layout
LIB=$LIB,polymer_localstorage
LIB=$LIB,polymer_media_query
LIB=$LIB,polymer_meta
LIB=$LIB,polymer_mock_data
LIB=$LIB,polymer_overlay
LIB=$LIB,polymer_page
LIB=$LIB,polymer_scrub
LIB=$LIB,polymer_selection
LIB=$LIB,polymer_selector
LIB=$LIB,polymer_shared_lib
LIB=$LIB,polymer_signals
LIB=$LIB,polymer_view_source_link

dartdoc --package-root=packages/ --out=doc --include-lib=$LIB lib/polymer_elements.dart
#
